trigger:
  branches:
    include:
      - main
      - develop
      - staging

pool:
  vmImage: ubuntu-latest

variables:
  - group: azure-static-web-apps-ambitious-flower-0d5923800-variable-group

jobs:
  - deployment: DeployFrontendToProd
    condition: eq(variables['Build.SourceBranchName'], 'main')
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            # Create .env.production file from variable group
            - task: PowerShell@2
              displayName: 'Create .env.production file'
              inputs:
                targetType: 'inline'
                script: |
                  Write-Host "Creating .env.production file..."
                  $envContent = @"
                  VITE_API_URL=$(VITE_API_URL)
                  VITE_LIST_PAGE_SIZE=$(VITE_LIST_PAGE_SIZE)
                  "@
                  $envContent | Out-File -FilePath ".env.production" -Encoding UTF8
                  Write-Host "Created .env.production file with environment variables"
                  Get-Content ".env.production"

            - task: AzureStaticWebApp@0
              inputs:
                azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_0D5923800)
                app_location: "/"
                api_location: ""
                output_location: "dist"

  - deployment: DeployFrontendToDev
    condition: ne(variables['Build.SourceBranchName'], 'main')
    environment: 'Demo'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            # Create .env.production file from variable group
            - task: PowerShell@2
              displayName: 'Create .env.production file for dev'
              inputs:
                targetType: 'inline'
                script: |
                  Write-Host "Creating .env.production file for dev environment..."
                  $envContent = @"
                  VITE_API_URL=$(VITE_API_URL)
                  VITE_LIST_PAGE_SIZE=$(VITE_LIST_PAGE_SIZE)
                  "@
                  $envContent | Out-File -FilePath ".env.production" -Encoding UTF8
                  Write-Host "Created .env.production file with dev environment variables"
                  Get-Content ".env.production"

            - task: AzureStaticWebApp@0
              inputs:
                azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_0D5923800)
                app_location: "/"
                api_location: ""
                output_location: "dist"