trigger: none

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build application (includes linting)'